root = "."
tmp_dir = "tmp"

[build]
  # Tell Air to build from your main.go entry point
  cmd = "go build -o tmp/main -buildvcs=false ./cmd"
  bin = "tmp/main"
  full_bin = "dlv exec --continue --accept-multiclient --listen=:2345 --headless=true --api-version=2  --log --log-dest=/app/tmp/devel-debug.log ./tmp/main"

  # File watching config
  include_ext = ["go"]
  exclude_dir = ["vendor", "tmp", "bin"]
  delay = 1000
  log = "build.log"

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[debug]
  enable = true